spring:
  application:
    name: message-service

server:
  port: 8081

# http://localhost:8081

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org:
      simo:
        auth:
          context:
            provider: DEBUG