spring:
  application:
    name: auth-service-v2
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Auth-v2
      authentication-database: admin
      username: rootuser
      password: rootpass
      auto-index-creation: true

server:
  port: 8083

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token:
        expiration: 60000
      refresh-token:
        expiration: 604800000

user-service:
  health-check:
    enabled: false
    url: 'lb://user-service/user/health-check'
    delay: 60000
  auth:
    url:
      login: 'lb://user-service/user/login'
      register: 'lb://user-service/user/register'
