spring:
  application:
    name: default-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

server:
  port: 8080

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE

auth-service:
  validation:
    url: 'lb://auth-service/auth/validate'

public:
  routes:
  - /auth/**
  - /eureka/**
